# Generated by Django 5.1.8 on 2026-03-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_contentauditlog_target_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("unit_name", models.CharField(blank=True, max_length=200)),
                ("objectives", models.TextField()),
                ("key_points", models.TextField()),
                ("difficult_points", models.TextField(blank=True)),
                ("learning_methods", models.TextField(blank=True)),
                ("assignment_suggestion", models.TextField(blank=True)),
                ("order_no", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_guides",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_guides_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["course_id", "order_no", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "order_no"),
                        name="uniq_guide_order_per_course",
                    )
                ],
            },
        ),
    ]
