# Generated by Django 5.1.8 on 2026-04-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningfeedback",
            name="attitude_q10",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="attitude_q8",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="attitude_q9",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="class_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="knowledge_q1",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="knowledge_q2",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="knowledge_q3",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="knowledge_q4",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="overall_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "优秀"),
                    ("good", "良好"),
                    ("pass", "合格"),
                    ("improve", "待提高"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="practice_q5",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="practice_q6",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="practice_q7",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="reflection_advice",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="reflection_gain",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="reflection_gap",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="learningfeedback",
            name="student_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
