# Generated by Django 5.1.8 on 2026-02-24 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                            ("judge", "True / False"),
                            ("short", "Short Answer"),
                        ],
                        db_index=True,
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("stem", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.JSONField(default=list)),
                ("explanation", models.TextField(blank=True)),
                ("score", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "question_type"], name="idx_q_lesson_type"
                    ),
                    models.Index(fields=["difficulty"], name="idx_q_difficulty"),
                    models.Index(fields=["is_active"], name="idx_q_active"),
                ],
            },
        ),
    ]
