# Generated by Django 5.1.8 on 2026-02-24 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("total_score", models.PositiveIntegerField(default=0)),
                ("earned_score", models.PositiveIntegerField(default=0)),
                (
                    "accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to="courses.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.JSONField(blank=True, default=list)),
                ("expected_answer", models.JSONField(blank=True, default=list)),
                ("is_correct", models.BooleanField(default=False)),
                ("score_awarded", models.PositiveIntegerField(default=0)),
                ("explanation_snapshot", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission_id", "question_id"],
            },
        ),
        migrations.CreateModel(
            name="WrongQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wrong_count", models.PositiveIntegerField(default=1)),
                ("resolved", models.BooleanField(default=False)),
                ("first_wrong_at", models.DateTimeField(auto_now_add=True)),
                ("last_wrong_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_users",
                        to="quiz.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_wrong_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="quizsubmission",
            index=models.Index(
                fields=["user", "submitted_at"], name="idx_submission_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="quizsubmission",
            index=models.Index(
                fields=["lesson", "submitted_at"], name="idx_submission_lesson_time"
            ),
        ),
        migrations.AddIndex(
            model_name="quizanswer",
            index=models.Index(
                fields=["question", "is_correct"], name="idx_answer_q_correct"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="uniq_submission_question"
            ),
        ),
        migrations.AddIndex(
            model_name="wrongquestion",
            index=models.Index(
                fields=["user", "resolved"], name="idx_wrong_user_resolved"
            ),
        ),
        migrations.AddConstraint(
            model_name="wrongquestion",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="uniq_wrong_question_per_user"
            ),
        ),
    ]
