# Generated by Django 5.1.8 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizsubmission_quizanswer_wrongquestion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "单选题"),
                    ("multiple", "多选题"),
                    ("judge", "判断题"),
                    ("short", "简答题"),
                ],
                db_index=True,
                default="single",
                max_length=20,
            ),
        ),
    ]
