# Generated by Django 5.1.8 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumpost",
            name="category",
            field=models.CharField(
                choices=[("discussion", "讨论"), ("help", "求助"), ("share", "分享")],
                db_index=True,
                default="discussion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "已发布"),
                    ("hidden", "已隐藏"),
                    ("deleted", "已删除"),
                ],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
    ]
