# Generated by Django 5.1.8 on 2026-03-18 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_courseglossaryterm"),
        ("forum", "0002_alter_forumpost_category_alter_forumpost_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="forumpost",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to="courses.lesson",
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["lesson", "status"], name="idx_forum_lesson_status"
            ),
        ),
        migrations.AddField(
            model_name="forumpostlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="forum.forumpost",
            ),
        ),
        migrations.AddField(
            model_name="forumpostlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="forumpostlike",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="uniq_forum_post_like"
            ),
        ),
    ]
