# Generated by Django 5.1.8 on 2026-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_forumpostlike_forumpost_lesson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("discussion", "讨论"),
                    ("help", "求助"),
                    ("share", "分享"),
                    ("showcase", "成果展示"),
                ],
                db_index=True,
                default="discussion",
                max_length=20,
            ),
        ),
    ]
