# Generated by Django 5.1.8 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "教师"), ("admin", "管理员")],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
    ]
