# Generated by Django 5.1.8 on 2026-03-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("course", "课程"),
                            ("resource", "资源"),
                            ("guide", "教学指引"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(db_index=True)),
                ("title_snapshot", models.CharField(max_length=200)),
                ("url_snapshot", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "target_type", "target_id"),
                        name="uniq_favorite_user_target",
                    )
                ],
            },
        ),
    ]
