# Generated by Django 5.1.8 on 2026-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_favoriteitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteitem",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("course", "课程"),
                    ("resource", "资源"),
                    ("guide", "教学指引"),
                    ("post", "帖子"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
