# Generated by Django 5.1.8 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_chapter_is_active_lesson_is_active_contentauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentauditlog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("course", "课程"),
                    ("chapter", "章节"),
                    ("lesson", "课时"),
                    ("question", "题目"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("archived", "已归档"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
