# Generated by Django 5.1.8 on 2026-03-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_contentauditlog_target_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100)),
                ("definition", models.TextField()),
                ("order_no", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_terms",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course_id", "order_no", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "order_no"),
                        name="uniq_glossary_order_per_course",
                    )
                ],
            },
        ),
    ]
