# Generated by Django 5.1.8 on 2026-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("lesson", "Lesson"),
                            ("forum_post", "Forum Post"),
                            ("question", "Question"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("source_id", models.PositiveBigIntegerField(db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "is_active"],
                        name="idx_search_type_active",
                    ),
                    models.Index(fields=["updated_at"], name="idx_search_updated"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_id"), name="uniq_search_source"
                    )
                ],
            },
        ),
    ]
