# Generated by Django 5.1.8 on 2026-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchdocument",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("lesson", "Lesson"),
                    ("forum_post", "Forum Post"),
                    ("question", "Question"),
                    ("resource", "Resource"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
