# Generated by Django 5.1.8 on 2026-03-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_courseglossaryterm"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": [
                    "course_id",
                    "lesson_id",
                    "sort_order",
                    "-updated_at",
                    "-id",
                ]
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="audience",
            field=models.CharField(
                choices=[("all", "全体学习者"), ("teacher", "教师专用")],
                db_index=True,
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="sort_order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
